// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe7bI4bqtxjGhW7nq3HmzCxXQ6vHhG3JQ',
    appId: '1:197017191026:web:bede3935705f47da3938eb',
    messagingSenderId: '197017191026',
    projectId: 'dapoeramiapp',
    authDomain: 'dapoeramiapp.firebaseapp.com',
    storageBucket: 'dapoeramiapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-BWl65TToifehwxJPcrIXXKOtdddbhLQ',
    appId: '1:197017191026:android:96b8e0521f6b045b3938eb',
    messagingSenderId: '197017191026',
    projectId: 'dapoeramiapp',
    storageBucket: 'dapoeramiapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkW3e6TtHZeYRyl01JgE167DtSSUm6Qo8',
    appId: '1:197017191026:ios:36a6d531d4a6ad093938eb',
    messagingSenderId: '197017191026',
    projectId: 'dapoeramiapp',
    storageBucket: 'dapoeramiapp.firebasestorage.app',
    iosBundleId: 'com.example.dapoerAmi',
  );
}
